### ISSUE TITLE
Incorrect test name

### ISSUE THREAD

**Issue by YewIsHot** [nesfit/ICS#95]
The name of the test suggests that it is not supposed to throw any exceptions. However, you then assert that it does.

Link to test: https://github.com/nesfit/ICS/blob/d07f477aef6638b511e53758d7e7305bb5d6321b/src/CookBook/CookBook.BL.Tests/RecipeFacadeTests.cs#L74

**Comment by pluskal** [comment]
Thanks, I made some polishing of tests here fc5ecd446fce628407b120a25518215f7dd76d0a
